image: tessera/cdh5mr2
script:
  - if [ -d /etc/drone.d ]; then
  -   for i in /etc/drone.d/*.sh; do
  -     if [ -r $i ]; then
  -       . $i
  -     fi
  -   done
  -   unset i
  - fi 
finotify:
  email:
    recipients:
      - rhafen@gmail.com