image: tessera/cdh5mr2
script:
  - rm -rf /usr/local/lib/R/site-library/Rhipe
  - sudo -i -u tessera cd `pwd`; ant build-distro -Dhadoop.version=cdh5
  - sudo -i -u tessera R -e "library(testthat); test_package('Rhipe')"
notify:
  email:
    recipients:
      - rhafen@gmail.com
