image: tessera/cdh5mr2
script:
  - sudo -i -u tessera echo $JAVA_HOME
  - rm -rf /usr/local/lib/R/site-library/Rhipe
  - sudo -i -u tessera cd `pwd`; ant build-distro -Dhadoop.version=cdh5; R CMD INSTALL Rhipe*.tar.gz
notify:
  email:
    recipients:
      - rhafen@gmail.com
