image: tessera/cdh5mr2
script:
  - sudo -i -u tessera printenv
  - chown tessera:tessera -R .
  - rm -rf /usr/local/lib/R/site-library/Rhipe
  - sudo -i -u tessera -- sh -c "cd `pwd`; ant build-distro -Dhadoop.version=cdh5; R CMD INSTALL Rhipe*.tar.gz"
  - for x in `cd /etc/init.d ; ls hadoop-hdfs-*` ; do service $x start ; done
  - service hadoop-yarn-resourcemanager start
  - service hadoop-yarn-nodemanager start
  - service hadoop-mapreduce-historyserver start
  - sudo -i -u tessera R -e "library(testthat); test_package('Rhipe')"
notify:
  email:
    recipients:
      - rhafen@gmail.com