image: tessera/cdh5mr2
script:
  - for x in `cd /etc/init.d ; ls hadoop-hdfs-*` ; do service $x start ; done
  - service hadoop-yarn-resourcemanager start
  - service hadoop-yarn-nodemanager start
  - service hadoop-mapreduce-historyserver start
  - hadoop fs -ls /user
  - sudo -i -u tessera R -e "library(testthat); for(ff in list.files(file.path(system.file(package = 'Rhipe'), 'tests/testthat'), full.names = TRUE, pattern = '*.R')) source(ff)"
notify:
  email:
    recipients:
      - rhafen@gmail.com
